<a href="https://colab.research.google.com/github/zenitsu0705/DM/blob/main/Rescale%26Bin%26stan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Rescale 

In [4]:
from numpy import asarray

In [5]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
data = asarray([[200,0.001],[300,0.05],[260,0.001],[800,0.5]])
data

array([[2.0e+02, 1.0e-03],
       [3.0e+02, 5.0e-02],
       [2.6e+02, 1.0e-03],
       [8.0e+02, 5.0e-01]])

In [11]:
scaler = MinMaxScaler()

In [12]:
scaled = scaler.fit_transform(data)
scaled

array([[0.        , 0.        ],
       [0.16666667, 0.09819639],
       [0.1       , 0.        ],
       [1.        , 1.        ]])

In [13]:
from sklearn import datasets
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [14]:
irisdata = datasets.load_iris()
irisdata

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [15]:
x = irisdata.data
y = irisdata.target

In [16]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [17]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1,stratify=y)
mm = MinMaxScaler()

In [19]:
x1 = mm.fit_transform(x_train)
x2 = mm.transform(x_test)

In [20]:
x1

array([[0.33333333, 1.        , 0.06779661, 0.04166667],
       [0.30555556, 0.63636364, 0.11864407, 0.04166667],
       [0.58333333, 0.54545455, 0.72881356, 0.91666667],
       [0.66666667, 0.59090909, 0.79661017, 0.83333333],
       [0.19444444, 0.54545455, 0.03389831, 0.04166667],
       [0.66666667, 0.5       , 0.77966102, 0.95833333],
       [0.91666667, 0.45454545, 0.94915254, 0.83333333],
       [0.41666667, 0.90909091, 0.03389831, 0.04166667],
       [0.80555556, 0.45454545, 0.81355932, 0.625     ],
       [0.63888889, 0.40909091, 0.61016949, 0.5       ],
       [0.19444444, 0.13636364, 0.38983051, 0.375     ],
       [0.25      , 0.31818182, 0.49152542, 0.54166667],
       [0.11111111, 0.54545455, 0.05084746, 0.04166667],
       [0.5       , 0.36363636, 0.62711864, 0.45833333],
       [0.33333333, 0.22727273, 0.50847458, 0.5       ],
       [0.41666667, 0.31818182, 0.69491525, 0.75      ],
       [0.13888889, 0.63636364, 0.15254237, 0.04166667],
       [0.19444444, 0.        ,

In [21]:
x2

array([[0.52777778, 0.63636364, 0.74576271, 0.91666667],
       [0.30555556, 0.86363636, 0.11864407, 0.125     ],
       [0.08333333, 0.63636364, 0.06779661, 0.08333333],
       [0.16666667, 0.22727273, 0.59322034, 0.66666667],
       [0.63888889, 0.45454545, 0.57627119, 0.54166667],
       [0.5       , 0.36363636, 0.50847458, 0.5       ],
       [0.66666667, 0.22727273, 0.81355932, 0.70833333],
       [0.52777778, 0.09090909, 0.59322034, 0.58333333],
       [0.58333333, 0.31818182, 0.72881356, 0.75      ],
       [0.30555556, 0.86363636, 0.05084746, 0.125     ],
       [0.38888889, 1.09090909, 0.08474576, 0.125     ],
       [0.5       , 0.45454545, 0.66101695, 0.70833333],
       [0.02777778, 0.40909091, 0.06779661, 0.04166667],
       [0.16666667, 0.18181818, 0.38983051, 0.375     ],
       [0.08333333, 0.54545455, 0.06779661, 0.04166667],
       [0.69444444, 0.36363636, 0.6440678 , 0.54166667],
       [0.72222222, 0.5       , 0.69491525, 0.91666667],
       [0.36111111, 0.45454545,

In [22]:
# Binarize Data

In [24]:
from sklearn.preprocessing import Binarizer
import pandas as pd
import numpy as np

In [26]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
colnames = ["preg","plas","pres","skin","ins","mass","depi","age","class"]

In [27]:
data = pd.read_csv(url,names=colnames)
data

preg  plas  pres  skin  ins  mass   depi  age  class
0       6   148    72    35    0  33.6  0.627   50      1
1       1    85    66    29    0  26.6  0.351   31      0
2       8   183    64     0    0  23.3  0.672   32      1
3       1    89    66    23   94  28.1  0.167   21      0
4       0   137    40    35  168  43.1  2.288   33      1
..    ...   ...   ...   ...  ...   ...    ...  ...    ...
763    10   101    76    48  180  32.9  0.171   63      0
764     2   122    70    27    0  36.8  0.340   27      0
765     5   121    72    23  112  26.2  0.245   30      0
766     1   126    60     0    0  30.1  0.349   47      1
767     1    93    70    31    0  30.4  0.315   23      0

[768 rows x 9 columns]

In [28]:
array = data.values
array

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [30]:
x = array[:,0:8]
y = array[:,8]

In [31]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [32]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [33]:
binarize = Binarizer(threshold=0.0).fit(x)

In [34]:
ans = binarize.transform(x)

In [43]:
ans[0:10,:]

array([[1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 0., 1., 1.]])

In [36]:
# Standardize Data

In [37]:
from sklearn.preprocessing import StandardScaler

In [41]:
scaler = StandardScaler().fit(x)

In [42]:
rescale = scaler.transform(x)
rescale[0:10,:]

array([[ 0.63994726,  0.84832379,  0.14964075,  0.90726993, -0.69289057,
         0.20401277,  0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575,  0.53090156, -0.69289057,
        -0.68442195, -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, -1.28821221, -0.69289057,
        -1.10325546,  0.60439732, -0.10558415],
       [-0.84488505, -0.99820778, -0.16054575,  0.15453319,  0.12330164,
        -0.49404308, -0.92076261, -1.04154944],
       [-1.14185152,  0.5040552 , -1.50468724,  0.90726993,  0.76583594,
         1.4097456 ,  5.4849091 , -0.0204964 ],
       [ 0.3429808 , -0.15318486,  0.25303625, -1.28821221, -0.69289057,
        -0.81134119, -0.81807858, -0.27575966],
       [-0.25095213, -1.34247638, -0.98770975,  0.71908574,  0.07120427,
        -0.12597727, -0.676133  , -0.61611067],
       [ 1.82781311, -0.184482  , -3.57259724, -1.28821221, -0.69289057,
         0.41977549, -1.02042653, -0.36084741],
       [-0.54791859,  2.38188392